#!/bin/bash

cd $HOME/ffmpeg/downloads
wget https://ffmpeg.org/releases/ffmpeg-4.0.tar.bz2
tar xjvf ffmpeg-4.0.tar.bz2
rm ffmpeg-4.0.tar.bz2
cd ffmpeg-4.0
PATH="$HOME/ffmpeg/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg/lib/pkgconfig"
./configure \
	--prefix="$HOME/ffmpeg" \
	--pkg-config-flags="--static" \
	--extra-cflags="-I$HOME/ffmpeg/include" \
	--extra-ldflags="-L$HOME/ffmpeg/lib" \
	--extra-libs="-lpthread -lm" \
	--bindir="$HOME/ffmpeg/bin" \
	--toolchain=hardened \
	--enable-gpl \
	--enable-nonfree \
	--disable-stripping \
	--enable-avisynth \
	--enable-libass \
	--enable-libbluray \
	--enable-libbs2b \
	--enable-libcaca \
	--enable-libcdio \
	--enable-libflite \
	--enable-libfontconfig \
	--enable-libfreetype \
	--enable-libfribidi \
	--enable-libgme \
	--enable-libgsm \
	--enable-libmysofa \
	--enable-libopenmpt \
	--enable-librubberband \
	--enable-librsvg \
	--enable-libshine \
	--enable-libsnappy \
	--enable-libssh \
	--enable-libtwolame \
	--enable-libwavpack \
	--enable-libxml2 \
	--enable-libzmq \
	--enable-libzvbi \
	--enable-omx \
	--enable-openal \
	--enable-opengl \
	--enable-sdl2 \
	--enable-libdc1394 \
	--enable-libdrm \
	--enable-libiec61883 \
	--enable-chromaprint \
	--enable-frei0r \
	--enable-libopencv \
	--enable-libsrt \
	--enable-libaom \
	--enable-ladspa \
	--enable-libpulse \
	--enable-libsoxr \
	--enable-libspeex \
	--enable-avfilter \
	--enable-postproc \
	--enable-pthreads \
	--enable-libfdk-aac \
	--enable-libmp3lame \
	--enable-libopus \
	--enable-libtheora \
	--enable-libvorbis \
	--enable-libvpx \
	--enable-libx264 \
	--enable-libx265 \
	--enable-libkvazaar \
	--disable-ffplay \
	--enable-libopenjpeg \
	--enable-libwebp \
	--enable-libxvid \
	--enable-libvidstab \
	--enable-libopenh264 \
	--enable-zlib \
	--enable-openssl
PATH="$HOME/ffmpeg/bin:$PATH" make
sudo make install
make distclean
source ~/.profile
